CREATE TABLE tableName 
(
    Student name 	VARCHAR(512),
    Student ID number  	INT,
    GPA	INT
);

INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala khaled', '22230134', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar Ashraf Abbas', '22230229', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Adam Ramadan ', '22230211', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('روضة احمد عبدالحليم ', '22230094', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مهند عمرو فاروق ', '22230239', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمود ضياء محمود محمد', '22230188', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Belal Hany', '22230682', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohammed jameel Abdelrahman sharki', '22231142', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عمر سعيد عبدالحميد السيد ', '22230230', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('نعمة ثابت يوسف ', '22230322', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Michael Farid Fouad', '22230362', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Maryam Abdelmajeed', '22230476', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Logaen mohamed hossam ', '22230148', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nessma Saeed', '22230816', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed Ahmed ', '22230207', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ياسر محمد حسن محمد ', '22231120', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Carla wassim farouk naguib ', '22230737', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Baraa wael hassan ahmed', '22230562', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Lojaina sameh el sayed', '22230475', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أندرو أيمن صليب ', '22230855', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala Gamal Abd_Elfatah ', '22230659', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كيرلس سمير عبدالملاك ', '22231022', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Eman anwar ahmed', '22230075', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Razane abd el karim ', '22230452 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Ahmed ', '22230087', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Mohamed Ahmed Ghaleb', '22230896', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('انجى انور صفوت ', '22230701', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كريم نور الدين محمد حمزة ', '22230886', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Jana hussam eldin', '22230662', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('حنين صابر محمود ', '22230160', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nariman Ahmed Abd ElHafez Hassan ', '22230425', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrhman mohamd', '22230838', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed Ayman ', '22230830', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sama muhamed sami', '22230414', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar sherif mohamed ', '22230520', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('andrew Remon ', '22231007', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أروى محمود كامل مهران ', '22231006', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('زينه محمد سمير محمد ', '22230169', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Peter Nabil', '22230567', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('علي احمد سيد احمد ', '22231136', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ياسمين محمود حسين طنطاوي ', '22230780', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rania Amr Ahmed', '22230792', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marwan ahmed Mohammed', '22230883', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mazen Mohammed ', '22230280', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mazen Medhat atef', '22231133', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ShahdMohamedElian ', '22231114', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Bavly Marslious Gerges', '22231008', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marina Ezzat ', '22230440', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Holy Hany Shawky', '22230153', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سلمي محمد شعبان بركات ', '22230401', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala Abd elkhalek ramadan ', '22230568', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مونيكا عماد الفونس يني دوس ', '22230005', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Arwa ahmed saad ', '22230001', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ملك احمد عبدالحميد سيد احمد علام ', '22230396', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Seif Eddin Mohamed Salem', '22230513', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basel ahmed Aboelfetouh ', '22230521', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوسف هاني', '22230572', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('تقى اشرف ابراهيم مصطفى ', '22230344', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('جني رضا محمد عزب', '22230076', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nada abdalla hussien', '22230009', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شهد محمد عبد المجيد بدوي', '22230722', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('هيلين مينا شاكر فرنسيس', '22230064', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوستينا ماهر لمعي ', '22230784', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('نورهان شعبان احمد عبد الحليم', '22230141', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ندى أحمد محمد عوض الله ', '22230318', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('rana medhat wadie ', '22230439', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marwan Ahmed Abdel jalil', '22230681', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالرحمن مصطفى احمد ', '22230566', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES (' Salma Adel Shahin', '22230339', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ali A.Elnasser', '22230869', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أدهم علاء الدين عبد الله ', '22230046', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عمرو وائل محمد توفيق ', '22230542', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('اياد اشرف عبدالراضى ابراهيم', '22230028', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahman alaa ', '22230177', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مريم عايد محمد ', '22230663', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('خالد مصطفي السيد', '22230835', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Kerolos samuel hanna', '22230276', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yehya Ahmed Zenhom', '22230306', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ahmed mahmoud ', '22230888', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Radwa hisham kamal ', '22230144', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nader Hossam Mohamed Ahmed ', '22230899', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Malak ahmed fawzy shehata', '22230415', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Alaa Mohamed Hassan ', '22230929 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أسامة الهادي علي إبرهيم', '22230198', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohaned Ahmed ', '22230373', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كيرلس أشرف سمير ', '22230313', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يارا علاء محمد ', '22231050', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمد سامى محمد ', '22230268', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam essam ali', '22230122', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Seif Mohamed ', '22230369', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Habiba Waleed Abdelrazek ', '22230779', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Tamer Gaber Yassin', '22230758', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hagar Alsayed ', '22230112', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar saleh shazly', '22230826', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Martina Fady ', '22231118', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Wafik William ', '22231097', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كريم اكرم محمد ', '22230296', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sandy Medhat ', '22230432', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar karim salah eldein abdelwahab ', '22230985', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Verina emad abd almalek ', '22230710', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd mohamed mahmoud youssef', '22231122', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كيرلس ريمون موريس لبيب ', '22231052', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Karim ahmed hashem', '22230867', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rawan Sabry ', '22230803', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوسف محمود نادي', '22230924', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ziad ahmed nabil tosson', '22230291', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوسف محمد رشاد ', '22230632', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohand mohamd azmy', '22230882', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('marven magdy ', '22230893', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('چون سمير نبيل', '22230187', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سما محمد جابر عبدالجليل ', '22230379', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Khadiga Mohamed Hesham ', '22230813', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam ahmed farghaly ', '22230790', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Verina Hany Ragheb Gadallah', '22230713', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Saber', '22231048', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mostafa Yasser ', '22230950', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد حسام الدين مصطفى محمد ', '22230635', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Bahgat ayman', '22230698', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala tawfik Mohamed ', '22230418', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('رحمه اسعد عبد المنعم يوسف', '22230449', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssuf wael hassan', '22231035', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mohammd Abouelkheir ', '22230664', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Amr Khaled Mahmoud ', '22230209 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Farah magdy Ahmed ', '22230744', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالله محمود اسماعيل ', '22231018', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سيف علاءالدين حسين', '22230213', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مازن تامر', '22230559', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Menna lotfy hassan', '22230127', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Arwa Hassan Shaala', '22230338', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mostafa Kamal', '22230580', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Carol Nader ', '22230435', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Daniel wael', '22230512', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ضحي فهمي محمد', '22231014', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عمر محمد احمد عبد المؤمن', '22230975', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('منى محمد عبد الباسط', '22230164', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed waleed ', '22230887', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ashraf kamal Mohamed ', '22230910', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahman Ahmed Samir', '22230505', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سيف عبدالعزيز السيد', '22230032', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Madonna George Rizkallah ', '22230382', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hagar Elmoataz ', '22230126', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Wael ali ', '22230909', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Fatema el zahraa mohamed ', '22230390', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('جني اشرف كمال سليمان', '22230721', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marina Adel ', '22230116', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Catherine Osama Samir Gendy ', '22230804', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yasmin awad Ebrahim ', '22230436', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nada Medhat helal', '22230328', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mayar Ahmed Saad ', '22230794 ', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('toqa khaled kanz abdelrehem ', '22230003', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوسف محمد صلاح الدين', '22230596', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('abdelrahman alaa mohamed ', '22230200', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nada abd el sadek ahmed ', '22230648', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahenda tarek Mohamed ', '22230082', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مرفت سامي محمد فرج', '22230706', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ساندي السيد', '222230789', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ali Hesham Magdy ', '22230526', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Gana mohsen', '22231108', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Fardous mohamed abotalb ', '22231021', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شادي ياسر السيد ابراهيم ', '22230192', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('حبيبه رضا سيد', '٢٢٢٣٠١٥٢', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mostafa Mohammed Elsayed', '22230885', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrhman yasser Bahaa elden ', '22230244', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youstina nader ', '2223754', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('علي الحسيني السيد سليم ', '22230544', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sama Mohammed abdelaziz ', '22230099', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('معتصم عمرو نصر ', '22230589', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Jana amir seid ', '22230762', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Hassan Mokhtar ', '22230683 ', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Habiba Alamir ', '22230107', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('روان عزت قناوي رمضان ', '22230773 ', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('نانسي تامر محمد عبدالحميد ', '22230799', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed ahmed ', '22230977', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sara abdelaziz ', '22230095', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Pearly reda', '22230341', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nadine Ahmed Mohamed Ali ', '22230723', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Zuhair Kamel', '22230424', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أحمد إيهاب أحمد كمال', '22230220', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Farah abdelaleem', '22230760', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أحمد محمد أبوطالب ', '22230024', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hana Mohamed Ezzat ', '22230768', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala ayman mokhtar', '22231093', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('اميره اشرف محمد', '٢٢٢٣٠٣٧٨', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sama adel mohamed ', '22230085', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Maram Ihab monir', '22230411', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Doris hany', '22230467', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hana Hesham Mahmoud Kamel', '22231110', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يوسف مصطفى سعيد حسن ', '22230350', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rawan Ahmed', '22230376', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('زياد احمد محمد كمال الدين', '22230210', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ياسين هانى سعيد سيد ', '22230206', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('loujaina khaled abdallah', '22230124', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مهند مصطفي كمال الحنفي', '22230202', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nour zaki badr ', '22231116', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد حسام الدين محمد مهني', '22230240', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mai osama mohamed ', '22230481', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ندي عبدالعزيز شاكر ', '22230102', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmala sayed', '22230478', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شهد محمود احمد سعيد', '22230004', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hamid Ashraf Ahmed ', '22230504', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Radwa Ramadan Mahmoud Mohamed ', '22230755', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('جني سامح عبدالقادر', '22230174', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sama muhammed abdelfatah ', '22230165', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Islam mohamed kamal', '22230311', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed seif Elyazel kamel Ahamed', '22230654', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شهد حسين حسن ', '22230070', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Basmla osama', '22230786', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Salma Adel Hassen', '22230747 ', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مايا مدحت لطفي حسين ', '22230448', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Eshraka mohamed', '22230461', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yousef gomaa sayed', '22231001', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('mazen mohamed', '22230502', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد حسن عطيه ', '22230573', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مؤمن محمد أحمد ', '22230303', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Zena Tarek', '22230061', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('منه الله محمد عيد محمود', '22230801', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمد أحمد مجدي أحمد ابو العزم ', '22230948', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rana Alaa Hamdy ', '22230007 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mohamed Mohamed Abdallah ', '22230118', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mohamed Mohamed Abdallah ', '22230118', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yara hany mahmouf', '22230976', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Alaa Mahmoud ', '22230454', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahman Alhussein Mohammed ', '22230630', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Noran Ayman Hefny ', '22230727', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Menna mohamed ', '22230158', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ganna Ahmed Hassan Ibrahim ', '22230170', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Radwa sherif aziz mohamed ', '22230430', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('علي الدين محمد يوسف ابو الحجاج', '22230853', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سلمى احمد عليوة', '22230455', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Ahmed Mahmoud Elnemr ', '22230670', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Salma safwat', '22230676', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('pola mekhaeel shaker', '22230585', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Asser Mohammed Harhash ', '22230286', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('منة الله عويس عبدالعال ', '22230482', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Jasmen Ashour Hassan ', '22230132', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Reem youssef Mohamed ', '22230620', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sohiala mohamed ragab', '22230464', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marwan Hany Medhat Yakan Hussein', '22230488', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('youssef mohamed', '22230269', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Judy Ahmed samra', '22231003', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahma mostafa ', '22230284', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('jana medhat abd el monem', '22230788', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rofaida ihab', '22230155', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahman Rassmy', '22231104', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marwan Ahmed abdel Jalil', '22230681', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nada mohammed abdelzaher ', '22230080', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ءالاء احمد حسن محمد ', '22230471', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('khadija ghoneim', '22230345', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hamza Mohamed Saad Abdelmotalab ', '22230053', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('منة الله محمد سيد احمد', '22230133', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ganna Mostafa Mazhar', '22230808', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yehia ehab mohamed', '22230833', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef yasser mosa ', '22230234', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef yasser mosa ', '22230234', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marwan yosry', '22230824', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالله محمد عمر سيد عليوه', '22230597', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مريم حسام الدين علي محمد ', '22230472', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nada hany mohamed shaker ', '22230716', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('amr ahmed abass mohamed', '22230253', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مريم يحيي عطيه محمد ', '22230807', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('amr ahmed abass mohamed', '22230253', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Maria nashaat', '22230149', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed hesham fathy ', '22230299 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('mera amr mohamed ', '22230711', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Kareem Ayman ', '22230353', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef yasser', '22230248', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed mohamed aboalyoser', '22230563', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Karim mohamed kamal', '22230516', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Helana Maher', '22230705', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ندا أنور عبد العظيم على ', '22230809', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('John danial ', '22230551', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سارة عصمت', '22230384', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('يارا حسام الدين يحيي ', '22230413', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شهد محمد حامد ', '22230429', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('بسملة هاني عوض الله محمد ', '22230433', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ledia adel', '22230800', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar mohamed abdalfadil', '22230271', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('اسراء عبدالكريم عوض ', '22230672', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Melody Ayman', '22230785', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مريم محمد عبد الحميد ', '22230154', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('بيشوي ارميا شنوده', '22230039', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Maria sherif', '22230462', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Laila Gabr', '22230473', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Kerolos fady ayoub ', '22230538 ', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Toka khaled Mostafa ', '22230806', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('زياد وليد محمد محمد ', '22230974', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('أحمد محمد عبد الستار محمد ', '22230646', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد عبدالرحيم احمد', '22230281', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('"مريم محمد محروس');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('"', '22231044', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('فارس محمد مصطفى', '22231128', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rabab hassan', '22230333', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mazen mohamed shams el din', '22230871', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mark Emil Wadie Morcos ', '22231091', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سلمى محمد حمدالله محمود فرج ', '22230805', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abd El rahamn Abd Elhady', '22230372', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam walid', '22230738', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Fatma mohsen mohamed', '22230444', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('هبة عماد الدين فؤاد محمد ', '22231060', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد بهاء الدين علي (boha )', '22230326', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Ayman ', '22230453', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mahmoud Mohamed makser', '22230660', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Kirollos milad ', '22230503', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مافى سامح فوزى موسى ', '22230673', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yousef Mohamed ', '22230264', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Malak tarek mohamed', '22230742', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('نوران احمد عبد الحافظ محمد ', '22230018', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rama talla rabie', '22230097.', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Verina Hany Refaat ', '22230771', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('شهاب ساهر نبيل محمد', '22230251', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('rawan essam ibrahim', '22230428', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Kenzy yousry hamdy', '22230665', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالرحمن تامر علاءالدين ', '22230045', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Roaa sameh', '22230159', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Seif Waleed El Sayed Mohammed ', '22231112', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Angela heshmat samir', '22230138', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Gehan ali ', '22230336 ', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Essmat', '22230751', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Habiba mohamed', '22230446', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Walid ', '22230963', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yasmine ayman saad elkholy', '22230712', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed Ayman Mohamed ', '22230830', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كيرلس طاهر شاروبيم زاخر', '22230245', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed ahmed mohamed odam ', '22230991', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nagwa Hassan kamel ', '22230458', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed amr said ', '22230644', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('روضه مصطفي عبدالرحمن ', '22230443', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yassmin Mohamed Mahmoud ', '22230400', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sandy Ehab Elshamy ', '22230019', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('فاطمة محمد احمد محمد ', '22230015', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مارينا كمال ', '22230457', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed ahmed', '22230219', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد أسامة ربيع صادق ', '22230510', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Jowiria Hany Ahmed ', '22230385', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Menna mohamed monir', '22230330', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mohamed ', '22230108', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('علي محمد علي محمد ', '22230356 ', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('زياد مصطفى عبدالمنعم', '22230514', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Farah Fouad ', '22230456', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdelrahman ', '22230840', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Shahd Mohamed Hamed ', '22230091', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Batol mahmoud mohamed sadeq ', '22230724', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rawan Ahmed ', '22230815', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed Khaled salah', '22230923', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمود نادي محمود عبد الجواد ', '22231077 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hala Mohamed Esmail', '22230658', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('بسملة محمد جادالله بشير', '22230821', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rashed hani', '22230036', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef Amr Amin ', '22230927', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ganna hazem ahmed', '22230417', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Seif mohamed ahmed kamal', '22230282', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marly Hossam Mousa ', '22230072', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('فاطمه سعيد سعد ', '22230725', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سلمى احمد عبد الحافظ محمد ', '22230044', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('malak moataz mohamed abdullah', '22230022', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Lana Alnobi Abdelradi', '22230347', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef ashraf mohamed', '22230906', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Farah Yasser Ahmed', '22230090', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ziad osama abdallah', '22230940', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mariam Ahmed albadawy ', '22230651', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمد احمد حسين ', '22231064', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Olivia Ashraf Meshreky ', '22230479', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ali mohamed mohamed shawky', '22230866', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed Ashraf Abdel-Aal', '22230351', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Malak', '22230168', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('احمد محمد حسين محمد ', '22230962', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Jasmine Ahmed mohamed ', '22230405', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عمر حسني عبد العظيم محمود ', '22230190', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Aya sabri mohamed ', '22230402', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Malak mohsen Mohamed ', '22231030', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Rawan tarek', '22230013', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('amr ahmed abass mohamed', '22230253', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('mostafa alaa mohamed mahmoud ', '22231098', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mahmoud moataz mahmoud ', '22231027', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمد يسري حسين مسلم ', '22230638', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('سيف الدين ايهاب', '22230242', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mohamed Amr ', '22231036', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ريمون جرجس ', '22230649', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Arwa Ashraf Salem', '22230120', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمود عماد حمدي راتب ', '22230241', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ملك ياسين محجوب عبد المعطى', '22230119', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Yara hesham saeed ', '22230065', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('ahmed mohamed abdallah elbarbary ', '22230626', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nora mohamed saad', '22230135', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبد العزيز احمد محمود عيسوي', '22230543', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('محمد حسن محمد عبد المطلب', '22231004', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالرحمن محمد السيد ', '22230884', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Omar mohamed ', '22230628', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Aliaa Yasser Ibrahim ', '22230069', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Philopateer Maher Samir', '22230584', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Zeyad mahmoud ebrahim ', '22230368', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Merihan ', '22230002', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('مصطفى محمد عبدالعزيز', '22230854', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عزالدين عمرو عيسى امام ', '22230274', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Habiba tarek Mohamed', '22230445', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('christine youssef ', '22230423', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Hazem Mohamed Yousry', '22230228', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('اسلام ابراهيم صابر', '22230944', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sylvia Michel ', '22230057 ', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mustafa ayman Mustafa ', '22230278', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Youssef mohamed', '22230604', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Abdullah ahmed elshamy', '22230485', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('فرح وليد محمد عبد الحليم ', '22230777', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Marvy Ashraf wasfy ', '22230146', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nardine samir', '22230480', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Mira', '22230469 ', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('معاذ محمد سيد امين', '22230221', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('منه محمد كمال ', '22230419', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('تقي محمد عطالله ', '22230103', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Eslam adel Yehya Ouda', '22230935', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Farah Mohamed Abd El twab ', '22230434', '1');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عمر محمد محمود ابراهيم ', '22230979', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Menna Moustafa Mohamed ', '22231039', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Helen wageh ', '22230409', '1.5');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالرحمن حسانين السيد حسانين ', '22230653', '2.6');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('عبدالرحمن حسانين السيد حسانين ', '22230653', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('كنزي باسم مصطفي احمد ', '22230348', '2');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Ahmed hussein elgendy ', '22230047', '3');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Sara ahmed samy ', '22230123', '4');
INSERT INTO tableName (Student name , Student ID number  , GPA) VALUES ('Nouran Walid Ibrahim Mohamed Sakr', '22230142', '1');
